# Generated by Django 3.0 on 2019-12-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='album_title',
        ),
    ]
